# Generated by Django 4.0.4 on 2022-05-28 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ecg', models.FloatField(blank=True, null=True)),
                ('glucose', models.IntegerField(blank=True, null=True)),
                ('cardio', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
