# Generated by Django 4.0.4 on 2022-05-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='UserDataModel',
        ),
    ]
